GET http://localhost:8080/api/users/me 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzM2NzUxMDI1LCJleHAiOjE3MzkzNDMwMjV9.0jW58NA9kIQI9MalNDPZOgl9Mu3iqja010T8HVEf64I
